# Generated by Django 2.2.5 on 2019-10-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AllInOne', '0003_auto_20191003_0156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
